I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 60, in script
    $ initializing_things()
  File "game/script.rpy", line 60, in <module>
    $ initializing_things()
      ~~~~~~~~~~~~~~~~~~~^^
  File "game/initializing_things.rpy", line 2570, in initializing_things
    creating_new_expeditions()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "game/functions.rpy", line 301, in creating_new_expeditions
    Expedition(
    ~~~~~~~~~~^
        mission.title,
        ^^^^^^^^^^^^^^
    ...<4 lines>...
        mission.expedition_type
        ^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "game/classes.rpy", line 532, in __init__
    enemy = Protector(expedition_type, enemy_stage + 1, difficulty, "Available", expeditions_enemies_base_data, chosen_evolution_value)
            ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "game/classes.rpy", line 86, in __init__
    self.basePoints = protector_enemies_map[name].copy()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
AttributeError: 'BaseProtectorData' object has no attribute 'copy'

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/script.rpy", line 60, in script
    $ initializing_things()
  File "renpy/ast.py", line 1187, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1260, in py_exec_bytecode
    exec(bytecode, globals, locals)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "game/script.rpy", line 60, in <module>
    $ initializing_things()
      ~~~~~~~~~~~~~~~~~~~^^
  File "game/initializing_things.rpy", line 2570, in initializing_things
    creating_new_expeditions()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "game/functions.rpy", line 301, in creating_new_expeditions
    Expedition(
    ~~~~~~~~~~^
        mission.title,
        ^^^^^^^^^^^^^^
    ...<4 lines>...
        mission.expedition_type
        ^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "game/classes.rpy", line 532, in __init__
    enemy = Protector(expedition_type, enemy_stage + 1, difficulty, "Available", expeditions_enemies_base_data, chosen_evolution_value)
            ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "game/classes.rpy", line 86, in __init__
    self.basePoints = protector_enemies_map[name].copy()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
AttributeError: 'BaseProtectorData' object has no attribute 'copy'

Windows-11-10.0.26120-SP0 AMD64
Ren'Py 8.4.1.25072401
Protectors 1.0
Thu Sep  4 19:13:17 2025
