I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 38, in script call
    call see_all_missions(2)
  File "game/base_of_operations.rpy", line 61, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
[Previous line repeated 1 more time]
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
[Previous line repeated 1 more time]
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
[Previous line repeated 1 more time]
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
[Previous line repeated 1 more time]
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
[Previous line repeated 2 more times]
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/resting.rpy", line 4, in script
    python:
  File "game/resting.rpy", line 7, in <module>
    mission.updateDaysPassed()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "game/classes.rpy", line 303, in updateDaysPassed
    self.finishMission()
    ~~~~~~~~~~~~~~~~~~^^
  File "game/classes.rpy", line 362, in finishMission
    my_protectors_map[self.assignedProtectorName].missions_failed += 1
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     
AttributeError: 'Protector' object has no attribute 'missions_failed'

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 38, in script call
    call see_all_missions(2)
  File "game/base_of_operations.rpy", line 61, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
[Previous line repeated 1 more time]
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
[Previous line repeated 1 more time]
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
[Previous line repeated 1 more time]
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
[Previous line repeated 1 more time]
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
[Previous line repeated 2 more times]
  File "game/places.rpy", line 38, in script call
    call base_travel_menu()
  File "game/places.rpy", line 16, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_all_missions(1)
  File "game/base_of_operations.rpy", line 64, in script call
    call see_all_missions(1)
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/resting.rpy", line 4, in script
    python:
  File "renpy/ast.py", line 1187, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1260, in py_exec_bytecode
    exec(bytecode, globals, locals)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "game/resting.rpy", line 7, in <module>
    mission.updateDaysPassed()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "game/classes.rpy", line 303, in updateDaysPassed
    self.finishMission()
    ~~~~~~~~~~~~~~~~~~^^
  File "game/classes.rpy", line 362, in finishMission
    my_protectors_map[self.assignedProtectorName].missions_failed += 1
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     
AttributeError: 'Protector' object has no attribute 'missions_failed'

Windows-11-10.0.26120-SP0 AMD64
Ren'Py 8.4.1.25072401
Protectors 1.0
Tue Aug 19 16:43:32 2025
