I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/places.rpy", line 17, in script call
    call base_travel_menu()
  File "game/places.rpy", line 17, in script call
    call base_travel_menu()
  File "game/places.rpy", line 24, in script call
    call show_my_available_protectors(False)
  File "game/places.rpy", line 26, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 26, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 70, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 44, in script call
    call base_travel_menu()
  File "game/places.rpy", line 17, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 70, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 44, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 70, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 44, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 15, in script call
    call base_travel_menu()
  File "game/places.rpy", line 31, in script
    menu:
  File "game/screens.rpy", line 2651, in execute
    screen protector_detail_screen(my_protector):
  File "game/screens.rpy", line 2651, in execute
    screen protector_detail_screen(my_protector):
  File "game/screens.rpy", line 2654, in execute
    frame:
  File "game/screens.rpy", line 2659, in execute
    fixed:
  File "game/screens.rpy", line 2702, in execute
    vbox:
  File "game/screens.rpy", line 3081, in execute
    vbox:
  File "game/screens.rpy", line 3086, in execute
    $ current_status = my_protector.get_current_stats()
  File "game/screens.rpy", line 3086, in <module>
    $ current_status = my_protector.get_current_stats()
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "game/classes.rpy", line 383, in get_current_stats
    "strength": self.get_strength(fake_stage, fake_evolution),
                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "game/classes.rpy", line 239, in get_strength
    return int(self.basePoints.strength * used_stage * self.get_increments("Strength") * self.get_evolution_increments("Strength", fake_evolution))
                                                       ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^                                                             
  File "game/classes.rpy", line 439, in get_increments
    if prios["prio1"] == equipedBoots:
                         ^^^^^^^^^^^^ 
NameError: name 'equipedBoots' is not defined. Did you mean: 'self.equipedBoots'?

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/places.rpy", line 17, in script call
    call base_travel_menu()
  File "game/places.rpy", line 17, in script call
    call base_travel_menu()
  File "game/places.rpy", line 24, in script call
    call show_my_available_protectors(False)
  File "game/places.rpy", line 26, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 26, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 70, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 44, in script call
    call base_travel_menu()
  File "game/places.rpy", line 17, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 70, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 44, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 70, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 44, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 15, in script call
    call base_travel_menu()
  File "game/places.rpy", line 31, in script
    menu:
  File "renpy/ast.py", line 1815, in execute
    choice = renpy.exports.menu(choices, self.set, args, kwargs, item_arguments)
             ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/exports/menuexports.py", line 135, in menu
    rv = renpy.store.menu(new_items)
         ~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "renpy/exports/menuexports.py", line 418, in display_menu
    rv = renpy.ui.interact(mouse="menu", type=type, roll_forward=roll_forward)
         ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/ui.py", line 304, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/core.py", line 2219, in interact
    repeat, rv = self.interact_core(
                 ~~~~~~~~~~~~~~~~~~^
        preloads=preloads,
        ^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )  # type: ignore
    ^                
  File "renpy/display/core.py", line 2757, in interact_core
    root_widget.visit_all(lambda d: d.per_interact())
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/displayable.py", line 432, in visit_all
    d.visit_all(callback, seen)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "renpy/display/displayable.py", line 432, in visit_all
    d.visit_all(callback, seen)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "renpy/display/displayable.py", line 432, in visit_all
    d.visit_all(callback, seen)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "renpy/display/screen.py", line 503, in visit_all
    callback(self)
    ~~~~~~~~^^^^^^
  File "renpy/display/core.py", line 2757, in <lambda>
    root_widget.visit_all(lambda d: d.per_interact())
                                    ~~~~~~~~~~~~~~^^ 
  File "renpy/display/screen.py", line 514, in per_interact
    self.update()
    ~~~~~~~~~~~^^
  File "renpy/display/screen.py", line 715, in update
    self.screen.function(**self.scope)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "game/screens.rpy", line 2651, in execute
    screen protector_detail_screen(my_protector):
  File "game/screens.rpy", line 2651, in execute
    screen protector_detail_screen(my_protector):
  File "game/screens.rpy", line 2654, in execute
    frame:
  File "game/screens.rpy", line 2659, in execute
    fixed:
  File "game/screens.rpy", line 2702, in execute
    vbox:
  File "game/screens.rpy", line 3081, in execute
    vbox:
  File "game/screens.rpy", line 3086, in execute
    $ current_status = my_protector.get_current_stats()
  File "game/screens.rpy", line 3086, in <module>
    $ current_status = my_protector.get_current_stats()
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "game/classes.rpy", line 383, in get_current_stats
    "strength": self.get_strength(fake_stage, fake_evolution),
                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "game/classes.rpy", line 239, in get_strength
    return int(self.basePoints.strength * used_stage * self.get_increments("Strength") * self.get_evolution_increments("Strength", fake_evolution))
                                                       ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^                                                             
  File "game/classes.rpy", line 439, in get_increments
    if prios["prio1"] == equipedBoots:
                         ^^^^^^^^^^^^ 
NameError: name 'equipedBoots' is not defined. Did you mean: 'self.equipedBoots'?

Windows-11-10.0.26120-SP0 AMD64
Ren'Py 8.4.1.25072401
Protectors 1.0
Sun Sep  7 19:22:02 2025
